.TH "ScottFree" "6" 
.SH "NAME" 
scottfree \(em interpreter for Scott Adams database game files 
.SH "SYNOPSIS" 
.PP 
\fBscottfree\fP [\fB-d\fP]  [\fB-i\fP]  [\fB-y\fP]  [\fB-s\fP]  [\fB-t\fP]  [databasename]  [\fBsave-file\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBscottfree\fP command. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
Instead, it has documentation in text format; see below. 
.PP 
\fBscottfree\fP is a program that reads and 
executes TRS80 format Scott Adams datafiles. 
.SH "OPTIONS" 
.IP "\fB-d\fP         " 10 
Debugging info on load. 
.IP "\fB-i\fP         " 10 
Generate "I am"-style messages. (default) 
.IP "\fB-y\fP         " 10 
Generate "You are"-style messages. 
.IP "\fB-s\fP         " 10 
Generate authentic Scott Adams driver light messages rather 
than other driver style ones. 
.IP "\fB-t\fP         " 10 
Generate TRS80 style display. 
.SH "SEE ALSO" 
.PP 
/usr/share/doc/scottfree/ 
.SH "AUTHOR" 
.PP 
This manual page was written by Clint Adams <schizo@debian.org> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, 
Version 2 or any later version published by the Free 
Software Foundation. 
